import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Illustration from "@/ui/Illustration";
import Vine from "@/ui/Vine";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Illustration width={800} height={1000}>
          <Vine length={888} x={32} y={32} />
        </Illustration>
      </main>
    </>
  );
}
